# Generated by Django 5.2.1 on 2025-05-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_ID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=100)),
                ('member_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RecycleCenter',
            fields=[
                ('rc_ID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('rc_address', models.CharField(max_length=100)),
                ('rc_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('slide_ID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('slide_type', models.CharField(choices=[('Paper', 'Paper'), ('Can', 'Can'), ('Tin', 'Tin')], max_length=20)),
                ('slide_title', models.TextField()),
                ('slide_description', models.TextField()),
            ],
        ),
    ]
