# Generated by Django 4.1.4 on 2025-05-30 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slide_type',
            field=models.CharField(choices=[('paper', 'paper'), ('can', 'can'), ('tin', 'tin')], max_length=20),
        ),
        migrations.CreateModel(
            name='SlideComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('slide_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.slide')),
            ],
        ),
    ]
