# Generated by Django 4.1.4 on 2025-05-30 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_slide_slide_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidecomment',
            name='member_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.member'),
        ),
    ]
