# Generated by Django 4.1.4 on 2025-05-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_slidecomment_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclecenter',
            name='rc_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recyclecenter',
            name='rc_longitude',
            field=models.FloatField(null=True),
        ),
    ]
