# Generated by Django 4.1.4 on 2025-05-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_recyclecenter_rc_latitude_recyclecenter_rc_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclecenter',
            name='rc_address',
            field=models.TextField(),
        ),
    ]
