# Generated by Django 4.1.4 on 2025-05-31 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_recyclecenter_rc_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('region_latitude', models.FloatField()),
                ('region_longitude', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='recyclecenter',
            name='rc_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.region'),
        ),
    ]
