# Generated by Django 4.1.4 on 2025-05-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_region_recyclecenter_rc_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(choices=[('paper', 'paper'), ('plastic', 'plastic'), ('can', 'can'), ('tin', 'tin')], max_length=100, primary_key=True, serialize=False),
        ),
    ]
