# Generated by Django 4.1.4 on 2025-05-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_region_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(choices=[('puchong', 'puchong'), ('kajang', 'kajang')], max_length=100, primary_key=True, serialize=False),
        ),
    ]
