# Generated by Django 4.1.4 on 2025-06-01 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_region_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFoundRecycleCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_latitude', models.FloatField(null=True)),
                ('rc_longitude', models.FloatField(null=True)),
                ('rc_name', models.CharField(max_length=100)),
                ('rc_address', models.TextField()),
                ('rc_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
        ),
    ]
