# Generated by Django 4.1.4 on 2025-06-01 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_newfoundrecyclecenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfoundrecyclecenter',
            name='rc_submitby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.member'),
        ),
    ]
